[[main]]
name = "Blog"
pageRef = "posts"
weight = 10

[[main]]
name = "Projects"
pageRef = "projects"
weight = 20

[[main]]
name = "About"
pageRef = "about/index"
weight = 30

[[footer]]
name = "RSS Feed"
url = "./index.xml"
