colorScheme = "slate"
homepage.layout = "profile"
homepage.showRecent = true
mainPosts = ["posts"]
footer.showAppearanceSwitcher = true
enableSearch = true
footer.showScrollToTop = true
enableCodeCopy = true
autoSwitchAppearance = true
logo = "img/abhi-logo-white.png"
logoWhite = "img/abhi-logo-dark.png"