colorScheme = "slate"
homepage.layout = "profile"
homepage.showRecent = true
mainPosts = ["posts"]
showAppearanceSwitcher = true
enableSearch = true
showScrollToTop = true
enableCodeCopy = true
#logo = "img/abhi-logo-inverted.png"